### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by MHumm** [dbyoung720/ImageGray#1]
While I value what you try to schiebe, the inclusion of vcl.graphics.pas is a copyright violation. I doubt Embarcadero have you permission to publish this unit.
Why ist it needed here?

**Comment by dbyoung720** [comment]
Oh, let me see what to do.

When creating a large bitmap in memory, vcl.graphics.pas，it will be very time-consuming, so it has been modified.

**Comment by MHumm** [comment]
I know the issue of needing to copy a RTL/FMX/VCL file for modification...
If you can't come up with anyithing else you could leave off the file and put instructions 
about that you need to copy and modify it and what needs to be added in your documentation...
Another thing: if your modification is something more people would profit from, you might
create an official feature request in Quality Portal: https://www.quality.embarcadero.com
One fine day it might get included and spare you from needing to reapply your modification 
after each Delphi update.

Also be aware, that you need to reapply the modification for any new Delphi version!

**Comment by dbyoung720** [comment]
OK. thank.

**Comment by MHumm** [comment]
Did you create a feature request in Quality Portal about the thing you'd like to get improved in vcl.graphics.pas? If yes, I'd like to know the report number so I can track it and possibly vote for it as well.

**Comment by dbyoung720** [comment]
No. I just added a description in the readme.
